Scope India Website(Django Project)/subapp/urls.py
from django.urls import path
from .views import *
from . import views

urlpatterns = [
    path('', views.home, name='home'),
     path('about/', views.about, name='about'),
     path('contact/', views.contact, name='contact'),
     path('registration/', views.registration, name='registration'),
     path('form/',views.display_form, name='form'),
     path('mail', views.mail_send, name='mail'),
      path('password',views.gen_pass, name='genpass'),
      path('logout/', views.logout_view, name='logout'),
      path('signup/', views.sign, name='signup'),
    path('set-password/', views.set_new_password, name='set_new_password'),
    path('verify/', views.verify_temp_password, name='verify'),
    path('login/', views.login_view, name='login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    
     
]

Scope India Website(Django Project)/subapp/forms.py
from django import forms
from .models import *
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError


class studentform(forms.Form):
    name= forms.CharField(max_length=100)
    age= forms.IntegerField()
    email= forms.EmailField()
    gender= forms.CharField(widget=forms.RadioSelect(choices=[('male','Male'), ('female', 'Female'), ('others','Others')]))
    date_of_birth= forms.DateField()
    phone_number = forms.CharField(max_length=15)
    country= forms.CharField(widget=forms.Select(choices=[('india', 'India')]))
    state= forms.CharField(widget=forms.Select(choices=[('Tamil Nadu','Tamil Nadu'),('Kerala','Kerala'),('Andhra Pradesh','Andhra Pradesh'),('Telangana','Telangana'),('Odisha','Odisha'),('Karnataka','Karnataka'),('Goa','Goa'),('Haryana','Haryana'),('Bihar','Bihar')]))
    district=forms.CharField(widget=forms.Select(choices=[('Kanniyakumari','Kanniyakumari'),('Tirunelveli','Tirunelveli'),('Thoothukudi','Thoothukudi'),('Chennai','Chennai'), ('Coimbatore','Coimbatore'),('Kanchipuram','Kanchipuram'),('Vellore','Vellore')]))
    city=forms.CharField(widget=forms.Select(choices=[('Agasteeswaram','Agasteeswaram'),('Anjugramam','Anjugramam'),('Mylaudy','Mylaudy'),('Aralvaimozhi','Aralvaimozhi'),('Boothapandi','Boothapandi'),('Azhagappapuram','Azhagappapuram'),('Colachel','Colachel')]))
    hobbies= forms.CharField(widget=forms.CheckboxSelectMultiple(choices=[('Listening music','Listening music'), ('dancing','dancing'),('story writing','story writing'),('painting','painting'),('others','others')]))
    file= forms.FileField(required=False)
    
def clean(self) ->dict[str,any]:
       name=self.cleaned_data['name']
       age=self.cleaned_data['age']
       email=self.cleaned_data['email']
       gender=self.cleaned_data['gender']
       date_of_birth=self.cleaned_data['date_of_birth']
       phone_number=self.cleaned_data['phone_number']
       country=self.cleaned_data['country']
       state=self.cleaned_data['state']
       hobbies=self.cleaned_data['hobbies']
       file=self.cleaned_data['file']
        
       if name.islower():
           self.add_error('name', 'Name not in small letter')
       if age<=18:
           self.add_error('age', 'Age is not allowed')
       if email and not email.endswith("@gmail.com"):
           self.add_error('email', 'Email must be a gmail address.')
       valid_genders= ['male','female','others']
       if gender and gender not in valid_genders:
           self.add_error('gender', 'Invalid gender selection.')
       if file.size >2 * 1024 * 1024:
              self.add_error('file',"Files size should not exceed 2mb.")
              return self.cleaned_data


User = get_user_model()    
class loginform(forms.Form):
    username= forms.CharField()
    password= forms.CharField(widget=forms.PasswordInput)

def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        if username and password:
            try:
                stu = student.objects.get(email=username)
            except student.DoesNotExist:
                raise ValidationError("No student found with this email address.")

            # You can also check password validity here (if stored in plain text — not recommended)
            if stu.password != password:
                raise ValidationError("Incorrect password.")
        
        return cleaned_data

Scope India Website(Django Project)/subapp/templates/aboutus.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
<style>
    
    *{
            text-decoration: none;
        }
    body{
      margin: 0;
      font-family: sans-serif;
    }
    .navbar{
      background-color: rgb(24, 24, 87); 
      padding: 60px;
      border: 1px solid rgb(238, 230, 2);
        }
    .navdiv{
            display: flex; align-items: center; justify-content: space-between;
        }
    .topright {
      position: absolute;
      top: 10px;
      right: 50px;
      width: 200px;
    }

    .topleft1 {
      position: absolute;
      top: 20px;
      left: 50px;
      width: 150px;
      color: rgb(215, 158, 26);
    }

    .button1{
        position: absolute;
        top: 120px;
        right: 600px;
        
    }

    .button2{
        position: absolute;
        top: 120px;
        right: 480px;
    }

    .button3{
        position: absolute;
        top: 120px;
        right: 350px;
    }
    .button4{
        position: absolute;
        top: 120px;
        right: 200px;
    }
    .button5{
        position: absolute;
        top: 120px;
        right: 110px;
    }
    li{
            list-style: none; display: inline-block;
        }
    li a{
            color: white; font-size: 14; font-weight: bold; margin-right: 25px;
        }
    .color{
        color: rgb(170, 143, 22);
        background-color: rgb(24, 24, 87);
        
        border: 1px solid rgb(238, 230, 2);
    }
    

</style>

<nav class="navbar">
    <div class="navdiv">
      <img src="{%static 'image/scopeindia-logo.webp'%}" class="topleft1" alt="">
      <img src="{%static 'image/logo2.webp'%}"  class="topright" alt="">
      <ul>
        <li class="button1" ><a href="{%url 'home'%}">HOME</a></li>
        <li class="button2" ><a href="{%url 'about'%}">ABOUT US</a></li>
        <li class="button3"><a href="{%url 'contact'%}">CONTACT US</a></li>
        <li class="button4"><a href="{%url 'form'%}">REGISTRATION</a></li>
        <li class="button5"><a href="{%url 'login'%}">LOGIN</a></li>
      </ul>     
    </div>
</nav> 
</head>
<div class="color">
<center><h1 >Know About SCOPE INDIA</h1></center>
</div>
<body style="color: white; ">
    <div style=" background-color: rgb(38, 38, 118); padding:25px;">
    <center><h1 style="font-size: xxx-large;">SCOPE INDIA, your career partner!</h1><br>
    <b><p style="font-size: xx-large; line-height: 1.5;">One of India's best Training destinations for Software, Networking, DevOps and Cloud Computing courses with 18 years of Industrial experience. Over 1,000 students find their dream careers each year, and we have assisted more than 15,000 students so far.</p></b> <br>
    <p style="font-size: large; line-height: 2;">Software, Networking, and Cloud Professional Education Centre in Kerala and Tamil Nadu from Suffix E Solutions with WORKING PROFESSIONALS oriented on-the-job TRAINING model. SCOPE INDIA provides courses for Software Programming in Python (Data Science | Artificial Intelligence | Machine Learning | Deep Learning, Data Analytics), Java, PHP, .Net, MERN, Software Testing Manual and Automation, Cloud Computing (AWS | Azure), Server Administration (MicroSoft MCSE | Linux RHCE), Networking (CCNA), DevOps, Mobile App Development in Flutter, and Digital Marketing. A Training with a 100% Trusted Job-Based Internship Model. SCOPE INDIA has a Strong Placement Cell that provides jobs to thousands of students annually. We assure you, you won't regret it after training from SCOPE INDIA!

This is how SCOPE INDIA can support both newbies and those experienced in the industry to upgrade their skills.</p></center>
    </div>
</body>
        

  <style>
    
.footer {
  background-color: rgb(24, 24, 87);
  color: white;
  text-align: center;
  padding: 20px;
  border-top: 3px solid rgb(238, 230, 2);
  width: 98%;
  position: absolute;
  top: 900px;
  left: 0px;
      
}


  </style>
</head>
<body>
<div class="main-content">
  <footer class="footer">
    <p>We are located at Technopark TVM | Thampanoor TVM | Kochi, Kerala | Nagercoil, Tamil Nadu</p>
    <p>9745936073 (TPK) 9745936073 (TVM) 7592939481 (EKM) 8075536185 (NGL) info@scopeindia.org</p>
    <p>All Rights Reserved SCOPE INDIA & SUFFIX E SOLUTIONS PRIVATE LIMITED © 2007-2025 | Privacy Policy | Blog</p>
  </footer>
</div>
</body>
</html>

Scope India Website(Django Project)/subapp/templates/contact.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
<style>
    
    *{
            text-decoration: none;
        }
    body{
      margin: 0;
      font-family: sans-serif;
    }
    .navbar{
      background-color: rgb(24, 24, 87); 
      padding: 60px;
      border: 1px solid rgb(238, 230, 2);
        }
    .navdiv{
            display: flex; align-items: center; justify-content: space-between;
        }
    .topright {
      position: absolute;
      top: 10px;
      right: 50px;
      width: 200px;
    }

    .topleft1 {
      position: absolute;
      top: 20px;
      left: 50px;
      width: 150px;
      color: rgb(215, 158, 26);
    }

    .button1{
        position: absolute;
        top: 120px;
        right: 600px;
        
    }

    .button2{
        position: absolute;
        top: 120px;
        right: 480px;
    }

    .button3{
        position: absolute;
        top: 120px;
        right: 350px;
    }
    .button4{
        position: absolute;
        top: 120px;
        right: 200px;
    }
    .button5{
        position: absolute;
        top: 120px;
        right: 110px;
    }
    li{
            list-style: none; display: inline-block;
        }
    li a{
            color: white; font-size: 14; font-weight: bold; margin-right: 25px;
        }
    .color{
        color: rgb(170, 143, 22);
        background-color: rgb(24, 24, 87);
        
        border: 1px solid rgb(238, 230, 2);
    }
    .box1{
        background-color: rgb(33, 33, 116);
        padding: 100px;
        color: rgb(33, 126, 173);
    }
    .container {
      display: flex; justify-content: center; 
      align-items: center;  
    }
    .box2 {
      background-color: rgb(255, 255, 255);
      padding: 30px;
      margin: none;
      width: 45%;
      border-radius: 10px;
    }
    button{
      background-color: rgb(12, 2, 145); margin-left: 10px; border-radius: 10px; 
      padding: 10px; width: 400px; color: white; font-size: x-large;transition: all 0.1s ease-in-out;cursor: pointer;
    }
button:active {
   background-color: rgb(10, 2, 120); /* darker color when clicked */
  box-shadow: 0 2px #666;
  transform: translateY(4px); /* moves down when clicked */
}

</style>

<nav class="navbar">
    <div class="navdiv">
      <img src="{%static 'image/scopeindia-logo.webp'%}" class="topleft1" alt="">
      <img src="{%static 'image/logo2.webp'%}"  class="topright" alt="">
      <ul>
        <li class="button1" ><a href="{%url 'home'%}">HOME</a></li>
        <li class="button2" ><a href="{%url 'about'%}">ABOUT US</a></li>
        <li class="button3"><a href="{%url 'contact'%}">CONTACT US</a></li>
        <li class="button4"><a href="{%url 'form'%}">REGISTRATION</a></li>
        <li class="button5"><a href="{%url 'login'%}">LOGIN</a></li>
      </ul>     
    </div>
</nav> 

<div class="color">
    <center><h1>SCOPE INDIA Locations & Contact Details</h1></center>
  </div>

  <div style="background-color: rgb(255, 255, 255);" >
    <center><h2 style="color: rgb(24, 24, 87);">Center for Software, Networking, & Cloud Education</h2></center>
    <b><p style="color: rgb(77, 77, 216);">One of India's best Training destinations for Software, Networking, DevOps and Cloud Computing courses with 18 years of Industrial experience. Over 1,000 students find their dream careers each year, and we have assisted more than 15,000 students so far.</p></b>
  </div>
<body>
  
<div class="box1" >
    <div class="container">
      <div class="box2">
        <h1 style="color: rgb(156, 3, 3);">SCOPE INDIA Nagercoil 1, Tamil Nadu</h1>
        <h3>Near WCC College, Palace Rd, Nagercoil, Tamil Nadu 629001.</h3>
        <center>
        <button>8075536185</button><br><br>
        <a href="{%url 'mail'%}">
        <button>narmathanarmu186@gmail.com</button></a><br><br>
        <a href="https://www.google.com/maps/place/SCOPE+INDIA+Nagercoil+Data+Science+%26+AI,+Analytics,+DevOps,+Python,+PHP,+Java,+Dot+Net,+Flutter,+AWS,+Azure,+RHCE+Courses/@8.1851644,77.4263062,15z/data=!4m6!3m5!1s0x3b04f1a99bd30e13:0xa334f2091c02acd3!8m2!3d8.1851053!4d77.4264116!16s%2Fg%2F11trf6k0qx?entry=ttu&g_ep=EgoyMDI1MDYyMy4yIKXMDSoASAFQAw%3D%3D" target="_blank">
  <button>Location Route Map</button>
</a>
      </div>
    </div>
    </center>
</div>
</body>

  <style>
    
.footer {
  background-color: rgb(24, 24, 87);
  color: white;
  text-align: center;
  padding: 20px;
  border-top: 3px solid rgb(238, 230, 2);
  width: 98%;
  position: absolute;
  top: 900px;
  left: 0px;
      
}


  </style>
</head>
<body>
<div class="main-content">
  <footer class="footer">
    <p>We are located at Technopark TVM | Thampanoor TVM | Kochi, Kerala | Nagercoil, Tamil Nadu</p>
    <p>9745936073 (TPK) 9745936073 (TVM) 7592939481 (EKM) 8075536185 (NGL) info@scopeindia.org</p>
    <p>All Rights Reserved SCOPE INDIA & SUFFIX E SOLUTIONS PRIVATE LIMITED © 2007-2025 | Privacy Policy | Blog</p>
  </footer>
</div>
</body>
</html>

Scope India Website(Django Project)/subapp/templates/mail.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
<style>
    
    *{
            text-decoration: none;
        }
    body{
      margin: 0;
      font-family: sans-serif;
    }
    .navbar{
      background-color: rgb(24, 24, 87); 
      padding: 60px;
      border: 1px solid rgb(238, 230, 2);
        }
    .navdiv{
            display: flex; align-items: center; justify-content: space-between;
        }
    .topright {
      position: absolute;
      top: 10px;
      right: 50px;
      width: 200px;
    }

    .topleft1 {
      position: absolute;
      top: 20px;
      left: 50px;
      width: 150px;
      color: rgb(215, 158, 26);
    }

    .button1{
        position: absolute;
        top: 120px;
        right: 600px;
        
    }

    .button2{
        position: absolute;
        top: 120px;
        right: 480px;
    }

    .button3{
        position: absolute;
        top: 120px;
        right: 350px;
    }
    .button4{
        position: absolute;
        top: 120px;
        right: 200px;
    }
    .button5{
        position: absolute;
        top: 120px;
        right: 110px;
    }
    li{
            list-style: none; display: inline-block;
        }
    li a{
            color: white; font-size: 14; font-weight: bold; margin-right: 25px;
        }
    .color{
        color: rgb(170, 143, 22);
        background-color: rgb(24, 24, 87);
        
        border: 1px solid rgb(238, 230, 2);
    }
    .box1{
        background-color: rgb(33, 33, 116);
        padding: 100px;
        color: rgb(33, 126, 173);
    }
    .container {
      display: flex; justify-content: center; 
      align-items: center;  
    }
    .box2 {
      background-color: rgb(255, 255, 255);
      padding: 30px;
      margin: none;
      width: 45%;
      border-radius: 10px;
    }
    button{
      background-color: rgb(12, 2, 145); margin-left: 10px; border-radius: 10px; 
      padding: 10px; width: 400px; color: white; font-size: x-large;transition: all 0.1s ease-in-out;cursor: pointer;
    }
button:active {
   background-color: rgb(10, 2, 120); /* darker color when clicked */
  box-shadow: 0 2px #666;
  transform: translateY(4px); /* moves down when clicked */
}
form {
      margin: 50px; /* You can adjust as needed */
      margin-left: 100;
      margin-right: 100;
    }
.form-group {
    display: flex;
     /* Vertically align label and textarea */
    gap: 10px; /* Space between label and textarea */
  }

  .container {
      max-width: 800px;
      margin: 30px auto;
      padding: 20px;
      border: 1px solid #ddd;
      border-radius: 10px;
      box-shadow: 0 0 15px rgba(0,0,0,0.1);
      background-color: #e1f0fa;
    }
</style>

<nav class="navbar">
    <div class="navdiv">
      <img src="{%static 'image/scopeindia-logo.webp'%}" class="topleft1" alt="">
      <img src="{%static 'image/logo2.webp'%}"  class="topright" alt="">
      <ul>
        <li class="button1" ><a href="{%url 'home'%}">HOME</a></li>
        <li class="button2" ><a href="{%url 'about'%}">ABOUT US</a></li>
        <li class="button3"><a href="{%url 'contact'%}">CONTACT US</a></li>
        <li class="button4"><a href="{%url 'form'%}">REGISTRATION</a></li>
        <li class="button5"><a href="{%url 'login'%}">LOGIN</a></li>
      </ul>     
    </div>
</nav> 
<div class="container">
<body >
    <form action="{%url 'mail'%}" method="post" enctype="multipart/form-data" >
        {%csrf_token%}
        <label for="id_email">Email:</label>
        <input type="email" name="email" placeholder="Enter your mail"><br><br>
        <label for="id_subject">Subject:</label>
        <input type="text" name="subject" placeholder="Subject"><br><br>
      <div class="form-group">
        <label for="id_message">Message:</label>
        <textarea name="message" id="" cols="50" rows="10" placeholder="Enter your message"></textarea>
      </div><br>
      <label for="id_file">Upload file:</label>
        <input type="file" name="file" ><br><br><br>
        <button>send</button>

    </form>
</body>
</div>
</html>

  <style>
    
.footer {
  background-color: rgb(24, 24, 87);
  color: white;
  text-align: center;
  padding: 20px;
  border-top: 3px solid rgb(238, 230, 2);
  width: 98%;
  position: absolute;
  top: 760px;
  left: 0px;
      
}


  </style>
</head>
<body>
<div class="main-content">
  <footer class="footer">
    <p>We are located at Technopark TVM | Thampanoor TVM | Kochi, Kerala | Nagercoil, Tamil Nadu</p>
    <p>9745936073 (TPK) 9745936073 (TVM) 7592939481 (EKM) 8075536185 (NGL) info@scopeindia.org</p>
    <p>All Rights Reserved SCOPE INDIA & SUFFIX E SOLUTIONS PRIVATE LIMITED © 2007-2025 | Privacy Policy | Blog</p>
  </footer>
</div>
</body>
</html>

Scope India Website(Django Project)/subapp/templates/registration.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
<style>
    
    *{
            text-decoration: none;
        }
    body{
      margin: 0;
      font-family: sans-serif;
       background-color: azure;
      
    }
    .navbar{
      background-color: rgb(24, 24, 87); 
      padding: 60px;
      border: 1px solid rgb(238, 230, 2);
        }
    .navdiv{
            display: flex; align-items: center; justify-content: space-between;
        }
    .topright {
      position: absolute;
      top: 10px;
      right: 50px;
      width: 200px;
    }

    .topleft1 {
      position: absolute;
      top: 20px;
      left: 50px;
      width: 150px;
      color: rgb(215, 158, 26);
    }

    .button1{
        position: absolute;
        top: 120px;
        right: 600px;
        
    }

    .button2{
        position: absolute;
        top: 120px;
        right: 480px;
    }

    .button3{
        position: absolute;
        top: 120px;
        right: 350px;
    }
    .button4{
        position: absolute;
        top: 120px;
        right: 200px;
    }
    .button5{
        position: absolute;
        top: 120px;
        right: 110px;
    }
    li{
            list-style: none; display: inline-block;
        }
    li a{
            color: white; font-size: 14; font-weight: bold; margin-right: 25px;
        }
    .color{
        color: rgb(170, 143, 22);
        background-color: rgb(24, 24, 87);
        
        border: 1px solid rgb(238, 230, 2);
    }
    .box1{
        background-color: rgb(33, 33, 116);
        padding: 100px;
        color: rgb(33, 126, 173);
    }
    .container {
      display: flex; justify-content: center; 
      align-items: center;  
    }
    .box2 {
      background-color: rgb(255, 255, 255);
      padding: 30px;
      margin: none;
      width: 45%;
      border-radius: 10px;
    }
    button{
      background-color: rgb(12, 2, 145); margin-left: 10px; border-radius: 10px; padding: 10px; width: 400px; color: white; font-size: x-large;
    }

    .form-group {
      
      align-items: center;
    }
    .form-group label {
      margin-right: 5px;
      margin-inline-start: auto;
    }
    .form-group input {
      margin-right: 200px;
    }


    input[type="text"],
    input[type="number"],
    input[type="date"],
    input[type="phonenumber"],
    input[type="file"] {
        width: 300px; /* You can set to any size you like */
        height: 40px;
        font-size: 16px;
    }
     select {
        width: 300px; /* Adjust width as you like */
        height: 40px;
        font-size: 16px;
    }

</style>

<nav class="navbar">
    <div class="navdiv">
      <img src="{%static 'image/scopeindia-logo.webp'%}" class="topleft1" alt="">
      <img src="{%static 'image/logo2.webp'%}"  class="topright" alt="">
      <ul>
        <li class="button1" ><a href="{%url 'home'%}">HOME</a></li>
        <li class="button2" ><a href="{%url 'about'%}">ABOUT US</a></li>
        <li class="button3"><a href="{%url 'contact'%}">CONTACT US</a></li>
        <li class="button4"><a href="{%url 'form'%}">REGISTRATION</a></li>
        <li class="button5"><a href="{%url 'login'%}">LOGIN</a></li>
      </ul>     
    </div>
</nav> 

<style>

  form {
      margin: 50px; /* You can adjust as needed */
      margin-left: 100;
      margin-right: 100;
      
    }
    

    label {
      display: block;
      margin-bottom: 5px;
    }

    input, select {
      width: 60;
      padding: 5px;
      box-sizing: border-box;
    }

  
  button {
    margin-top: 10px;
    height: 45px;
    width: 150px;
    font-size: 18px;
  }
  .container {
      max-width: 1200px;
      margin: 30px auto;
      padding: 20px;
      border: 1px solid #ddd;
      border-radius: 10px;
      box-shadow: 0 0 15px rgba(0,0,0,0.1);
    }
</style>
<center><br>

  <h1 >REGISTRATION  FORM</h1></center><br>
  <big>
    <div class="container">
      <form action=" " method="post" enctype="multipart/form-data">
        {%csrf_token%}
        <div style="display: flex; gap: 50px;">
          <label for="id_name">Name:</label>
          <input type="text" name="name" id="id_name" placeholder="enter your name">
          <div style="color: red;">{{forms.name.errors}}</div>
          <br>

          <label for="id_age">Age:</label>
          <input type="number" name="age" id="id_age" placeholder="enter your age">
          <div style="color: red;">{{forms.age.errors}}</div>
          <br>
        </div><br>


        <div style="display: flex; gap: 50px;">
          <label for="id_email">Email:</label>
          <input type="text" name="email" id="id_email" placeholder="enter your email">
          <div style="color: red;">{{forms.email.errors}}</div>
          <br>

          <label for="id_date_of_birth">Date of Birth:</label>
          <input type="date" name="date_of_birth" id="id_date_of_birth" >
          <div style="color: red;">{{forms.date_of_birth.errors}}</div>
          <br>

        </div> <br>

        <div style="display: flex; gap: 50px;">
          <label for="id_phone_number">Phone number:</label>
          <input type="phonenumber" name="phone_number" id="id_phone_number" placeholder="enter your phone number">
          <div style="color: red;">{{forms.phone_number.errors}}</div>
          <br>

          <label>Gender:</label>
          {{ forms.gender }}  <!-- This automatically renders as a <select> tag -->
          <div style="color: red;">{{ forms.gender.errors }}</div><br>
            
        </div><br>

        <div style="display: flex; gap: 50px;">
            <label>Country:</label>
            {{ forms.country }}  <!-- This automatically renders as a <select> tag -->
            <div style="color: red;">{{ forms.country.errors }}</div><br>
    

            <label>State:</label>
            {{ forms.state }}  <!-- This automatically renders as a <select> tag -->
            <div style="color: red;">{{ forms.state.errors }}</div><br>
        </div><br>

        <div style="display: flex; gap: 50px;">
            <label>District:</label>
            {{ forms.district }}  <!-- This automatically renders as a <select> tag -->
            <div style="color: red;">{{ forms.district.errors }}</div><br>

            <label>City:</label>
            {{ forms.city }}  <!-- This automatically renders as a <select> tag -->
            <div style="color: red;">{{ forms.city.errors }}</div><br>
        </div><br>

        <div style="display: flex; gap: 50px;">
            <label>Hobbies:</label>
            {{ forms.hobbies }}  <!-- This automatically renders as a <select> tag -->
            <div style="color: red;">{{ forms.hobbies.errors }}</div><br>
        </div><br>

            <label for="id_file">Upload File:  </label>
            <input type="file" name="file" id="id_file">
            <div style="color: red;">{{forms.file.errors}}</div><br>
    
            <center> <button type="submit">Submit</button></center>

</form> 
    </div>
</big>
</div>

  <style>
    
.footer {
  background-color: rgb(24, 24, 87);
  color: white;
  text-align: center;
  padding: 20px;
  border-top: 3px solid rgb(238, 230, 2);
  width: 98%;
  position: absolute;
  top: 1100px;
  left: 0px;
      
}


  </style>
</head>
<body>
<div class="main-content">
  <footer class="footer">
    <p>We are located at Technopark TVM | Thampanoor TVM | Kochi, Kerala | Nagercoil, Tamil Nadu</p>
    <p>9745936073 (TPK) 9745936073 (TVM) 7592939481 (EKM) 8075536185 (NGL) info@scopeindia.org</p>
    <p>All Rights Reserved SCOPE INDIA & SUFFIX E SOLUTIONS PRIVATE LIMITED © 2007-2025 | Privacy Policy | Blog</p>
  </footer>
</div>
</body>
</html>